### ISSUE TITLE
`\eta_2`

### ISSUE THREAD

**Issue by bwesterb** [mmcloughlin/mathfmt#14]
I would expect it to be formatted as η₂.

(Let me just reiterate that I absolutely love this tool.)

**Comment by mmcloughlin** [comment]
Ah, thanks for reporting this. Unfortunately the regular expressions for this are a mess, attempting to match math formulae while excluding other uses of underscores in text followed by numbers. Here's a nasty example drawn from some real code:

https://github.com/mmcloughlin/mathfmt/blob/32dcc2c9d4d78d2684a3bd43a6cb5db2076277a4/format_test.go#L113

I think #15 should fix this case you mentioned. Please report any other errors.
